### ISSUE TITLE
Not that I use it but Ponyr...

### ISSUE THREAD

**Issue by ghost** [Alzarath/Booru-Cogs#7]
Fails to do anything if you don't have tags.

Traceback (most recent call last):
  File "lib\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Programs\Red Bot\Red-DiscordBot\cogs\pony.py", line 31, in ponyr
    await fetch_image(self, ctx, randomize=True, tags=text)
  File "C:\Programs\Red Bot\Red-DiscordBot\cogs\pony.py", line 142, in fetch_image
    if not tags and self.filters[server.id] == []:
KeyError: '222510474686627840'

**Comment by Alzarath** [comment]
Thanks for reporting this issue. Fixed with cd59240.
